### ISSUE TITLE
Verschiedene Modi, in denen der Server laufen kann (development, staging, production)

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/socha#107]
Aehnlich wie bei Ruby on Rails sollte der Server in verschiedenen Modi laufen koennen. In Abhaengigkeit dessen kann man dann das Logging anpassen und verschiedene andere Dinge tun. So ist es auch weniger wahrscheinlich, dass eine Debugging-Aenderung in den Produktivbetrieb gelangt.

**Comment by Xerus2000** [comment]
Der server hat jetzt eine logback, logback-release und logback-production - muss hier noch was getan werden?
