### ISSUE TITLE
Möglichkeit, ein Spiel ohne Reservierungscodes zu beobachten

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/socha#108]
In der alten GUI hatten wir eine Option „manuell gestarteter Client“ bei der Spielerstellung. Die GUI hat dann ein offenes Spiel erstellt und gewartet, bis sich der/die manuell gestarteten Clients verbunden haben. Dann konnte man das Spiel ganz normal in der GUI spielen bzw. beobachten.

Anwendungsfall ist, dass die Schüler ihren Client in Eclipse oder irgendwie anders entwickeln und dann testweise starten, um ein Spiel gegen den Client in der GUI zu spielen. Mit der alten GUI ging das ueber die „manuell gestarteter Client“ Option ohne weiteres.

Diese Möglichkeit brauchen wir auch wieder in der neuen GUI, die aber nicht direkt im Server eingebettet ist, sondern als administrativer Observer handelt. Im Moment kann die GUI ein neues Spiel erstellen und beobachten, das ist dann aber (soweit ich weiß) immer ein Spiel mit Reservierungscodes. Die GUI kann die Reservierungscodes an den Benutzer weitergeben und der kann diese an die manuell gestarteten Clients weitergeben, das ist aber sehr umständlich.

Eventuell geht es auch schon (durch die Erweiterungen für Massentests). Wenn dem so ist, muss das aber noch dokumentiert werden, damit es in die GUI eingebaut werden kann.

**Comment by soerendomroes** [comment]
Die Massentests arbeiten ebenfalls mit den Reservierungen und startet dann die Clients und übergibt ihnen mit -r <code> (glaube ich) die Reservierungscodes (das könnte dann einfach angezeigt werden, dass der Client so gestartet werden muss). Wenn nicht durch Reservierung sondern durch join ein Spiel gestartet wird, weiß ich nicht genau, ob der Administratorclient, dann ebenfalls einfach an die roomId rankommt um sich als Observer zu verbinden bzw. ob er überhaupt eine Rückmeldung über den Start eines Spiels bekommt.

**Comment by SKoschnicke** [comment]
> Wenn nicht durch Reservierung sondern durch join ein Spiel gestartet wird, weiß ich nicht genau, ob der Administratorclient, dann ebenfalls einfach an die roomId rankommt um sich als Observer zu verbinden bzw. ob er überhaupt eine Rückmeldung über den Start eines Spiels bekommt.

Das Problem sehe ich auch. Aber ich weiß keine andere Möglichkeit, den von mir beschriebenen Anwendungsfall umzusetzen. Also müssen wir wahrscheinlich den Server um diese Funktion erweitern.

**Comment by soerendomroes** [comment]
implemented in 5533f2a73d647eaa6205f81e682e45c9aa5ae22d
