### ISSUE TITLE
server - Aktueller Sever läuft nur einen Schritt

### ISSUE THREAD

**Issue by oldaniel** [CAU-Kiel-Tech-Inf/socha#114]
Wenn man sich den aktuellen Server runterlädt, sowie den aktuellen Client fertig als `.jar` kann man nur einen Schritt laufen. Danach funktioniert nichts mehr.

Wenn man aber dann den Server über den GUI Client starte (`version 1.2.1`), dann funktioniert wieder alles. **Bitte hiermit um Behebung.**

**Comment by SKoschnicke** [comment]
Vielen Dank fuer den Fehlerbericht! Wir werden uns darum kuemmern.

Der aktuelle Server startet die Spiele pausiert. Die GUI hebt diese Pause wieder auf, daher funktioniert es mit der GUI, ohne aber nicht. Man kann dieses Verhalten des Servers in der Datei `server.properties` (eine einfache Textdatei, die im gleichen Verzeichnis wie die `software-challenge-server.jar` liegt) umstellen, indem man dort die Zeile:
```
paused = true
```
in 
```
paused = false
```
aendert.

In der naechsten Version wird diese manuelle Einstellung dann nicht mehr notwendig sein.

**Comment by SKoschnicke** [comment]
@apexys benoetigt die GUI fuer das Durchfuehren von Spielen mit manuell gestarteten Clients noch einen Server der Spiele pausiert startet? Falls nein, @Poehli bitte aendere die Build-Scripte so, dass die Pausen-Funktion ueber die `server.properties` deaktiviert ist.
