### ISSUE TITLE
The `gameEnded` method is not called in an error situation

### ISSUE THREAD

**Issue by matthesjh** [CAU-Kiel-Tech-Inf/socha#121]
Currently, the `gameEnded` method of an `IGameHandler` instance is only called when the round limit expires or a player reaches the goal. But due to the fact that the function has an `errorMessage` parameter it should also be called if e.g. one player sends an invalid move or leaves the game.

**Comment by soerendomroes** [comment]
If a PlayerClient did not cause the error it will receive the `GameResult` and hence the `gameEnded` method is called. The server closes its connection with a client that caused an error. Such a client will never receive the `GameResult`.

**Comment by matthesjh** [comment]
Is there any progress being made on this issue?

**Comment by SKoschnicke** [comment]
das guckt @soerendomroes sich nochmal an

**Comment by matthesjh** [comment]
@soerendomroes Is the problem fixed?

**Comment by soerendomroes** [comment]
Ich dachte ja, gab es da wieder Probleme mit?

**Comment by Xerus2000** [comment]
Solange hier keiner sagt, was eigentlich genau gemacht werden soll, schließe ich das mal.
