### ISSUE TITLE
Einen GameState laden funktioniert nicht mehr

### ISSUE THREAD

**Issue by soerendomroes** [CAU-Kiel-Tech-Inf/socha#125]
Mit dem Server aus einer Datei den start-Gamestate laden hat Fehler.

**Comment by soerendomroes** [comment]
Der entsprechende Dialog fehlt in der Gui

**Comment by soerendomroes** [comment]
Schleife `for (Class<?> clazz : this.clazzes) {` mit clazzes enthält GameState wird kein mal durchlaufen in `Gameloader.onNewState()`.

**Comment by soerendomroes** [comment]
8258aab111cdffc912fc4d81d532963627d7b639

**Comment by Xerus2000** [comment]
scheint aktuell zu funktionieren
