### ISSUE TITLE
Gradle statt Ant

### ISSUE THREAD

**Issue by Xerus2000** [CAU-Kiel-Tech-Inf/socha#129]
Gradle ist ein wesentlich versatileres buildtool und praktisch der Nachfolger von Ant und Maven. 

Somit kann man die Bibliotheken durch Gradle fetchen statt sie mit runterzuladen. Außerdem lassen sich Anpassungen am buildscript dann auch leicht vornehmen.

Das ist natürlich vor allem relevant für die Vorlage um den eigenen Client zu entwickeln, die hier nicht mit im Repository zu sein scheint.

**Comment by Xerus2000** [comment]
```
plugins {
    java
    application
}

dependencies {
    compile(files(file("lib").listFiles()))
}

java.sourceSets.getByName("main").java.srcDir("src")

application {
    applicationName = "Jumper"
    mainClassName = "xerus.softwarechallenge.Starter"
}
```

Das ist mein gradle buildscript (build.gradle.kts im root-Verzeichnis des Projekts) und es funktioniert problemlos.

**Comment by SKoschnicke** [comment]
Danke fuer den Vorschlag!

Wir haben das diskutiert und sehen derzeit keinen Mehrwert darin, in diesem Projekt Ant durch Gradle zu ersetzen.

**Comment by Xerus2000** [comment]
Ich denke der größte Vorteil wäre das einfache fetchen von Bibiliotheken von repositories, so könnten updates der Bibiliotheken auch ohne ein erneutes downloaden des simpleclients vorgenommen werden.
