### ISSUE TITLE
sc.networking.clients.XStreamClient DataDump Loglevel

### ISSUE THREAD

**Issue by Xerus2000** [CAU-Kiel-Tech-Inf/socha#139]
Im Log eines manuell gestartetetn Clients findet sich ständig der DataDump des XStreamClient auf Level WARN. Sollte das nicht auf DEBUG laufen?

**Comment by SKoschnicke** [comment]
Ich glaube das haben wir schon geaendert:

https://github.com/CAU-Kiel-Tech-Inf/socha/blob/c17b41d2346a1153a3828c7af2747813487e36fb/software_challenge_sdk/src/server_api/sc/networking/clients/XStreamClient.java#L124

Kommt dann im naechsten Release.
