### ISSUE TITLE
Log enthält unhilfreiche Nachrichten

### ISSUE THREAD

**Issue by Xerus2000** [CAU-Kiel-Tech-Inf/socha#144]
![image](https://user-images.githubusercontent.com/13354331/36512501-f9316d10-176a-11e8-9464-e4ec9b9db57c.png)

Diese Nachricht sehe ich dauernd im Log, manchmal mehrfach hintereinander, und sie liefert mir überhaupt keine Informationen...

**Comment by Xerus2000** [comment]
ahc und da gibt es noch das "HardTimout"

**Comment by SKoschnicke** [comment]
> ach und da gibt es noch das "HardTimout"

kannst du das genauer erklaeren?

**Comment by Xerus2000** [comment]
da ist ein rechtschreibfehler drin ;)

**Comment by Xerus2000** [comment]
Scheint alles gefixt zu sein
