### ISSUE TITLE
Unterschiedliche Standard-Ports für Testserver und GUI

### ISSUE THREAD

**Issue by Xerus2000** [CAU-Kiel-Tech-Inf/socha#161]
Wenn ein Testserver aktiv ist, können in der GUI keine Spiele gestartet werden. Ich denke dies ließe sich recht einfach durch unterschiedliche Standard-Ports beheben.

**Comment by SKoschnicke** [comment]
Gute Idee!

- [ ] Testserver lauscht auf Port 
- [ ] Enduser Doku anpassen (Clients muessen alternativen Port verwenden) https://cau-kiel-tech-inf.github.io/socha-enduser-docs/#automatische-spiele
- [ ] Shell-Scripte fuer die Testspiele anpassen
- [ ] Server muss den Standard-Port verwenden, wenn er im Wettkampfsystem laeuft!

**Comment by SKoschnicke** [comment]
Bitte noch in den Enduser-Docs einen Satz, dass die automatischen Testdurchlaeufe den Port 13051 und nicht 13050 wie sonst verwenden, damit das nochmal deutlicher wird. Im Moment steht der 13051 nur in den Start-Kommandos der Doku. Ausserdem gibt es im gleichen Dokument noch einen Absatz "Testdurchläufe" wo im Moment sowas wie "nicht unterstuetzt" steht. Dort bitte auf den Testclient verweisen (und auf den Abschnitt weiter unten wo dessen Nutzung erlaeutert wird).

**Comment by Xerus2000** [comment]
Ein entsprechendes PR ist offen in `socha-enduser-docs`, ich weiß jetzt nicht genau ob noch was fehlt. Aber die neue Dokumentation müsste dann auch mal deployed werden, die auf der Website ist recht alt.

**Comment by SKoschnicke** [comment]
Dann sollten wir das nochmal pruefen, wenn CAU-Kiel-Tech-Inf/socha-enduser-docs#10 gemerged ist.

**Comment by Xerus2000** [comment]
wie siehts aus?

**Comment by SKoschnicke** [comment]
Alles gemerged und online.
