### ISSUE TITLE
Lib folder is in git

### ISSUE THREAD

**Issue by soerendomroes** [CAU-Kiel-Tech-Inf/socha#170]
Soll der lib Ordner wirklich mit im git sein und wenn ja, warum?

**Comment by Xerus2000** [comment]
In der gitignore wird der lib Ordner für Hase und Igel ignoriert. Wahrscheinlich wurde das gitignore einfach noch nicht geupdatet bzw. nicht ordentlich generalisiert.

**Comment by Poehli** [comment]
Nein soll es nicht.
Siehe #169 im letzten commit.
