### ISSUE TITLE
Spiel wird beendet, obwohl Blau noch (als zweiter in der Runde) einen Zug machen duerfte

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/socha#179]
Ausgangssituation, Rot beginnt die Runde:
![zug34](https://user-images.githubusercontent.com/105162/44524330-6195f180-a6dd-11e8-9cd8-deebf0eed21e.png)
Rot macht einen Zug von J3 auf H5 (und frisst den einzigen blauen Fisch, der noch nicht zum blauen Schwarm gehört):
![zug35](https://user-images.githubusercontent.com/105162/44524338-6bb7f000-a6dd-11e8-9821-51cf8e6913a9.png)

Damit beendet der Server das Spiel. Laut Regeln müsste aber Blau noch einmal ziehen, da jede Runde zu Ende gespielt wird, bevor der Sieger feststeht, oder?

**Comment by soerendomroes** [comment]
Ok, ich schreibe dafür einen Test

**Comment by Xerus2000** [comment]
Ich unassigne mich mal. Wenn ihr mich hier doch noch braucht gerne assignen, aber ich denke Sören macht das ;)

**Comment by soerendomroes** [comment]
Sören kann das nur machen, wenn er auch unter windows bauen kann

**Comment by Xerus2000** [comment]
Ich habe die problematische Task erstmal aus dem Build rausgenommen, du solltest wieder arbeiten können :D
