### ISSUE TITLE
Testclient startet unter linux nicht

### ISSUE THREAD

**Issue by soerendomroes** [CAU-Kiel-Tech-Inf/socha#182]
Ich bekomme beim starten der start-test.sh den Fehler, dass das Mainattribute von test-client.jar nicht gesetzt ist

**Comment by Xerus2000** [comment]
Das liegt nicht an Linux, sollte auf anderen OS genauso sein. Ich weiß das Problem schon, und werde es fixen sobald ich wieder am PC bin.
