### ISSUE TITLE
Javadocs: Encoding der generierten HTML Seiten ist nicht UTF-8

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/socha#183]
Siehe zum Beispiel hier: https://www.software-challenge.de/javadocs/sc/plugin2019/package-summary.html

> Ein Spieler fÃ¼r Piranhas

Ich habe es hiermit versucht: https://stackoverflow.com/questions/25912190/how-to-set-an-encoding-for-the-javadoc-in-gradle bin aber gescheitert (will heissen, das Encoding hat sich im generierten HTML nicht geaendert, obwohl ich die `options.encoding` auf `"UTF-8"` gesetzt habe, alle anderen Ansaetze von der Seite haben Compiler-Fehler verursacht)

**Comment by Xerus2000** [comment]
Ich kann das Problem nicht reproduzieren, daher kann ich auch nicht testen ob eine Veränderung funktioniert. Also werde ich ein PR erstellen, dann kannst du testen ob das geht.

**Comment by SKoschnicke** [comment]
Ist bei dir das Encoding der generierten HTML Seiten auf UTF-8 gesetzt? Oder zeigt dein Browser das richtig an?

**Comment by Xerus2000** [comment]
Woran kann ich das erkennen? Der Fehler ist da, wenn ich auf deine URL gehe, aber wenn ich die doc selbst generiere ist sie immer korrekt. Vielleicht liegt das daran, dass ich grad auf Linux bin?

**Comment by Xerus2000** [comment]
#184

**Comment by SKoschnicke** [comment]
Nein, bin auch unter Linux und oeffne die lokal generierten Docs mit Firefox. Da sieht man den Fehler auch. In "Page Info" steht auch das falsche Encoding (windows-1252).

```
./gradlew build
firefox build/deploy/doc/index.html
(Rechtsklick -> Page Info)
```


![firefoxencoding](https://user-images.githubusercontent.com/105162/45021551-1f9c7200-b032-11e8-8b66-41870fa27f43.png)

**Comment by SKoschnicke** [comment]
Liegt vielleicht daran, dass mein System auf Englisch gestellt ist. Sollte aber natuerlich auch dann funktionieren. JavaDoc kann das Encoding in ein Meta-Tag in den HTML-Seiten schreiben, nur Gradle bekommt man das nicht gesagt. Wenn man sich den Source der HTML Seiten ansieht, gibt es kein entsprechendes Meta-Tag. Auch mit der encoding Option.

**Comment by SKoschnicke** [comment]
Problem besteht auch mit #184 (hatte ich schon versucht)

**Comment by Xerus2000** [comment]
```
 ~/daten/projects/socha/build/deploy/doc/sc/plugin2019 file -i package-summary.html
package-summary.html: text/html; charset=utf-8
```

Passiert bei mir so, ohne jede Option.
