### ISSUE TITLE
Attach Source bei JARs die beim SimpleClient Source ZIP mitgeliefert werden

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/socha#186]
Da man mit der Quellcode-Version des SimpleClients anfaengt zu entwickeln, waere es gut, wenn an die beiden relevanten JARs, `piranhas_2019.jar` und `software-challenge-sdk.jar` die Sourcen "attached" werden (jedenfalls beschwert sich Eclipse, wenn man sich den Code von GameState etc. ansehen will). Bei der JAR-Version des SimpleClient ist das weniger wichtig, aber wenn es nur allgemein geht, ist das auch okay.

**Comment by Xerus2000** [comment]
wie attached man das?

**Comment by Xerus2000** [comment]
im sinne von, eine sources-jar mit in die libs packen?

**Comment by SKoschnicke** [comment]
Irgendwie so, ja.
https://stackoverflow.com/questions/46747240/how-to-attach-the-source-to-the-jar-in-the-gradle-eclipse-project-when-the-sourc
