### ISSUE TITLE
Server erklärt Rot zum Gewinner, ohne das Ende der Runde abzuwarten

### ISSUE THREAD

**Issue by YouMe2** [CAU-Kiel-Tech-Inf/socha#191]
Auszug aus den Regeln: Blau könnte also einen roten Schwarm noch in der 2. Hälfte einer Runde wieder zerstören.
Der Server beendet aber das Spiel bereits nach dem Zug von Rot.

**Comment by SKoschnicke** [comment]
Der Fehler sollte eigentlich in der aktuellen Version behoben worden sein (siehe #179).

Welches Serverversion wird genutzt? Gibt es dazu ein Replay?

**Comment by YouMe2** [comment]
ahh ohhh jap ich hatte die alte version ausgeführt xD
sry
