### ISSUE TITLE
GUI nicht auf mac ausführbar

### ISSUE THREAD

**Issue by Lasse05** [CAU-Kiel-Tech-Inf/socha#192]
Hallo ich kann das sc 19 gut auf meinem mac mit neuestem java nicht ausführen bzw das Fenster wird und bleibt weiß.

**Comment by Xerus2000** [comment]
Wenn wir das nächste Release machen, wird es von travis auf MacOS gebaut, vielleicht reicht das ja schon.

**Comment by matthesjh** [comment]
Ich kann bestätigen, dass die neueste Version (19.1.4) der GUI unter macOS 10.14.3 mit Java 11.0.2 funktioniert. Das Problem sollte sich also gelöst haben.
