### ISSUE TITLE
Wrong parameter name in documentation

### ISSUE THREAD

**Issue by TiLuHa** [CAU-Kiel-Tech-Inf/socha#203]
In der Dokumentation zum Test-Client steht, dass die Namen der Attribute für die Timeouts "--timeout1" und "--timeout2" heißen. Der richtige Name lautet jedoch "--no-timeout1" bzw. "--no-timeout2"

**Comment by matthesjh** [comment]
@TiLuHa Vielen Dank für den Hinweis! Da wurde wohl vergessen, die Dokumentation zu aktualisieren.

**Comment by matthesjh** [comment]
@Xerus2000 Du hast mit 43977f6 die Namen der Argumente verändert. Ich würde diese Namensänderung allerdings wieder rückgängig machen, da für mich der Präfix `no-` bei dieser booleschen Option nich viel Sinn ergibt. Es ist eher verwirrend.

Was denkst du?

**Comment by Xerus2000** [comment]
Doch, das hat den Sinn, dass man boolesche Optionen nur angeben oder nicht angeben kann. Und standardmäßig sollten beide ja timeouten. Ich dachte ja erst dass man dann `--timeout1 false` angibt, aber das geht so nicht. Daher habe ich es andersrum gemacht.

**Comment by matthesjh** [comment]
Alles klar! Ich wusste nicht, dass bei booleschen Optionen keine nachfolgenden Werte angegeben werden können. Damit ergibt das für mich auch Sinn. Die Dokumentation sollte dann aber entsprechend geändert werden.
