### ISSUE TITLE
Endscreen anpassen

### ISSUE THREAD

**Issue by Agent77326** [CAU-Kiel-Tech-Inf/socha#213]
Der Endscreen ist noch von Piranha, des weitern scheint ein Problem bei der Farbentscheidung wer der Sieger ist zu existieren

**Comment by Agent77326** [comment]
https://github.com/CAU-Kiel-Tech-Inf/socha-gui/issues/53

**Comment by SKoschnicke** [comment]
Ich vermute das Problem eher bei der GUI, aber ich gucke mal.

**Comment by SKoschnicke** [comment]
Allerdings ist der Text mit dem Schwarm natuerlich vom Server. Aber das mit den Farben ist glaube ich ein GUI-Problem.

**Comment by SKoschnicke** [comment]
Behoben durch cf84b9c
