### ISSUE TITLE
getPossibleMoves implementieren

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/socha#216]
Brauchen wir fuer den SimpleClient, in der GUI gibt es schon eine Implementierung (fuer ein bestimmtes Feld). Man kann also einfach alle eigenen Steine durchgehen und die possibleMoves fuer jeden Stein zu einer grossen Liste zusammenfassen.

**Comment by Agent77326** [comment]
Man muss hierbei aber auch noch die Performance-Issues bedenken, welche noch bei der GUI sind (ist 100% Brute-Force) https://github.com/CAU-Kiel-Tech-Inf/socha-gui/issues/7

**Comment by SKoschnicke** [comment]
Implementiert durch a0bd3c1
(Performance machen wir noch)
