### ISSUE TITLE
Spider-/Beetlemove-Validation currently incorrect

### ISSUE THREAD

**Issue by Agent77326** [CAU-Kiel-Tech-Inf/socha#221]
GUI-Referenzen: [Beetle](https://github.com/CAU-Kiel-Tech-Inf/socha-gui/pull/67/commits/cb6e6948ad278bfcd47afe531a06f70bfc49b6da) und ~[Spider](https://github.com/CAU-Kiel-Tech-Inf/socha-gui/pull/67/commits/49c0b7cb7b444557b5c82ec7c4f013d5d0ed34ad) (outdated)~

**Comment by SKoschnicke** [comment]
und https://github.com/CAU-Kiel-Tech-Inf/socha-gui/issues/73

**Comment by SKoschnicke** [comment]
und https://github.com/CAU-Kiel-Tech-Inf/socha-gui/issues/74

**Comment by Agent77326** [comment]
Siehe https://github.com/CAU-Kiel-Tech-Inf/socha-gui/blob/1be9e94e6890562c0d8657382b81d9db8c127740/src/api/rules/HiveGameRules.ts#L87 für Spider

**Comment by SKoschnicke** [comment]
2f37eb801e4227b4cdf4326eee7fbdd98f89975e
