### ISSUE TITLE
Build-Script baut auch Piranhas Not-So-Simple-Client

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/socha#223]
Ich habe ihn bei den Releases jetzt manuell auf GitHub geloescht, sollte aber, bis wir einen fuer Hive haben, nicht mit gebaut und veroeffentlicht werden.

**Comment by Xerus2000** [comment]
folgende Überlegung: mit der minor version 1 wird immer der simpleclient released. Dann könnte ich automatisch bestimmte skripte danach checken lassen und einige tests und builds erst ab minor version 1 aktivieren, das würde auch diese Problem lösen
ich implementiere es jetzt mal so, wir können ja sonst details noch ändern, aber ich möchte solche Sachen die jedes Jahr passieren automatisieren

**Comment by Xerus2000** [comment]
oh moment, jetzt bin ich etwas durcheinander gekommen. Naja, wir können es aber trotzdem so machen, dass die offiziellen Versionen, die feature-complete sind, ab minor version 1 beginnen.
