### ISSUE TITLE
SimpleClient sendet ungültige Züge

### ISSUE THREAD

**Issue by sunfl0w** [CAU-Kiel-Tech-Inf/socha#224]
Ich habe gerade mal den SimpleClient testen wollen, leider versucht dieser ungültige Züge zu machen. Ich weiß nicht inwiefern dies mit anderen hier gemeldeten Fehlern zusammenhängt.

**Comment by Agent77326** [comment]
Danke für das Feedback, hängt vor allem daran vermutlich: #221 #217

**Comment by SKoschnicke** [comment]
Sollte dann jetzt korrekt funktioneren.
