### ISSUE TITLE
Undeployed pieces werden nicht mehr gesendet wenn rot keine mehr hat

### ISSUE THREAD

**Issue by Agent77326** [CAU-Kiel-Tech-Inf/socha#225]

**Comment by Xerus2000** [comment]
was genau ist das Problem? Für mich sieht alles korrekt aus.

**Comment by Agent77326** [comment]
![image](https://user-images.githubusercontent.com/27964795/65775392-60d15980-e140-11e9-9832-d387d1f645c3.png)
Nach dem setzen des letzten undeployed red, sendet der server nur noch leere listen für undeployed

**Comment by Xerus2000** [comment]
Ich habe einen state erzeugt, alle red pieces entfernt und das kam dabei raus:
```xml
<state startPlayerColor="RED" currentPlayerColor="RED" turn="0">
  [...]
  <undeployedRedPieces/>
  <undeployedBluePieces>
    <piece owner="BLUE" type="BEE"/>
    <piece owner="BLUE" type="SPIDER"/>
    <piece owner="BLUE" type="SPIDER"/>
    <piece owner="BLUE" type="SPIDER"/>
    <piece owner="BLUE" type="GRASSHOPPER"/>
    <piece owner="BLUE" type="GRASSHOPPER"/>
    <piece owner="BLUE" type="BEETLE"/>
    <piece owner="BLUE" type="BEETLE"/>
    <piece owner="BLUE" type="ANT"/>
    <piece owner="BLUE" type="ANT"/>
    <piece owner="BLUE" type="ANT"/>
  </undeployedBluePieces>
</state>
```
Sieht für mich valide aus.

**Comment by Agent77326** [comment]
Hm... ich schau mal in der gui bei der konversation

**Comment by Xerus2000** [comment]
ich vermute er parsed das shorthand tag nicht richtig

**Comment by Agent77326** [comment]
Bei fetchBackend returned er bereits einen leeren Array ![image](https://user-images.githubusercontent.com/27964795/65776457-7cd5fa80-e142-11e9-8f1a-35113a53fc58.png)
![image](https://user-images.githubusercontent.com/27964795/65776529-a0994080-e142-11e9-9e2e-557811c5389c.png)

Falls es hilft: hier ist auch der log...
[software-challenge-gui-2019.9.27.log.html.zip](https://github.com/CAU-Kiel-Tech-Inf/socha/files/3663115/software-challenge-gui-2019.9.27.log.html.zip)

**Comment by Xerus2000** [comment]
Ich schiebe das zur gui, liegt nicht am Server.
