### ISSUE TITLE
logback.xml wird beim SimpleClient / player nicht beachtet

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/socha#226]
Es scheint immernoch Probleme mit der logback Konfiguration zu geben. Die Einstellungen in der logback.xml werden nicht beachtet.

Muss nochmal untersucht werden.

Man sollte einfach die Ausgabe des XML-Protokolls im Log steuern koennen (ein-/ausschalten).

**Comment by Xerus2000** [comment]
könnte daran liegen: https://github.com/CAU-Kiel-Tech-Inf/socha/pull/233/commits/aa80f3a4dbe0ffb27d91fa6580dda31d89a82778
hatte ich vor ewigkeiten gefixt und nie gemerged ^^

**Comment by Xerus2000** [comment]
weißt du ob die Schüler die dieses Problem haben gradle nutzen?

**Comment by SKoschnicke** [comment]
Nein, weiss ich nicht.

Ich glaube aber, dass auch mit existierender `logback.xml` die Einstellungen darin nicht uebernommen werden. Jedenfalls hatte ich sicher ueberprueft, ob die Datei *vorhanden* ist.

**Comment by Xerus2000** [comment]
sie war vorhanden, wurde aber nicht in die player jar kopiert. Habe es behoben und in DIscord für die Schüler ein info-announcement gemacht
