### ISSUE TITLE
DeepCopy Gamestate

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/socha#227]
Wir brauchen eine einfache Moeglichkeit, eine DeepCopy eines Gamestate zu erzeugen.

**Comment by Xerus2000** [comment]
Sollte mit https://github.com/CAU-Kiel-Tech-Inf/socha/commit/a92114439555cedbebe596501db02bbfa070ac21 gefixt sein

**Comment by SKoschnicke** [comment]
https://github.com/CAU-Kiel-Tech-Inf/socha/blob/4c7a1a724be9490dfc5b0b517f8e188dd0135d6f/plugin/src/shared/sc/plugin2020/Board.kt#L118

Die Fields werden nicht geklont, sondern nur an das neue Board rangehaengt.

**Comment by Xerus2000** [comment]
Ah stimmt. Deswegen sollten Fields auch eigentlich immutable sein -_- dann spart man sich hier nämlich viel Arbeit

**Comment by SKoschnicke** [comment]
Da koennte ich mir vorstellen, dass es wieder mit XStream Probleme gibt, wenn die immutable sind.

**Comment by SKoschnicke** [comment]
In Release 20.1.0 behoben 655c0d6846eabd2e35a606e94212e2b21dea6d6f
