### ISSUE TITLE
Unterschied zwischen gedownloadeten Repo und runtergeladenen Simple-Client-Source

### ISSUE THREAD

**Issue by sunfl0w** [CAU-Kiel-Tech-Inf/socha#236]
Wenn ich den Simple-Client in meiner Kopie des Repos selber deploye, erhalte ich andere Methodensignaturen, als wenn ich den Simple-Client-Source-Code als Zip runterlade und nutze.
Zum Beispiel ist der Rückgabewert der Methode getPossibleMoves() beim selber deployen List<Move>, mit dem Code aus der Zip ist der Rücggabewert List<IMove>. Ich denke da liegt ein Fehler vor.

**Comment by Xerus2000** [comment]
ja, das liegt wohl an kürzlichen breaking changes. Wenn du das nicht meinst, öffne das issue gern wieder.
