### ISSUE TITLE
Klonen eines GameStates und das Ausführen von Zügen darauf funktioniert nicht.

### ISSUE THREAD

**Issue by sunfl0w** [CAU-Kiel-Tech-Inf/socha#238]
Hier mal etwas Code zum testen. Der Code an sich ist nicht unbedingt sinnvoll, löst aber den besagten Fehler aus.

```java
GameState state = gameState.clone();
for(int i = 0; i < 30; i++) {
    List<GameState> childGameStates = GetChildGameStates(state);
    state = childGameStates.get(0);
}
```

```java
private List<GameState> GetChildGameStates(GameState gameState) {
    List<GameState> childGameStates = new ArrayList<GameState>();
    List<Move> possibleMoves = GameRuleLogic.getPossibleMoves(gameState);

    for(Move move : possibleMoves) {
        GameState childGameState = gameState.clone();
        GameRuleLogic.performMove(childGameState, move);
        childGameStates.add(childGameState);
    }
    return childGameStates;
}
```

**Comment by Xerus2000** [comment]
@sunfl0w ah, mir war nicht bewusst, dass es hier auch ums klonen geht. Die clone-Methode war ja wie gesagt bis vor kurzem verbuggt. Bitte öffne das issue wieder, wenn es mit der in Kürze veröffentlichten neuen Version auch nicht klappt.

**Comment by sunfl0w** [comment]
Das Klonen des LastMove funktioniert soweit ich das beurteilen kann. Leider führt der oben aufgelistete Code immer noch zu einem Absturz des Programm mit dem Fehler: "sc.shared.InvalidMoveException: Piece is not a undeployed piece of the current player".

**Comment by sunfl0w** [comment]
Der rote Spieler setzt seine Biene zuesrt auf (-5,0,-5). Der blaue versucht seine auf (-4,-1,5) zu setzen. Dann tritt der Fehler auf.

**Comment by sunfl0w** [comment]
Hier noch ein weiteres Beispiel, dass diesen Fehler verursacht:

![clone](https://user-images.githubusercontent.com/22620672/67796511-71972700-fa80-11e9-9637-81190d3626fe.PNG)

**Comment by niklasCarstensen** [comment]
Beide Codebeispiele funktionieren bei mir.
Letzteres wirft nur ne Fehlermeldung wenn es in der 4. Runde keine Möglichkeit gibt die Biene zu setzen. Da wäre es sicherlich noch schöner wenn der Client aufgeben könnte, statt abzustürzen oder einen invaliden Move zu senden, aber das Issue kann man schließen meiner Ansicht nach.

**Comment by sunfl0w** [comment]
Das war aber glaube ich auch noch mit einer älteren Version. Wenn es jetzt funktioniert ist das ja sehr gut.
