### ISSUE TITLE
Die Move-Klasse hat keine Getter-Methoden, um Informationen über einen Zug zu bekommen.

### ISSUE THREAD

**Issue by sunfl0w** [CAU-Kiel-Tech-Inf/socha#240]
Ich denke, dass das noch praktisch wäre.

**Comment by Xerus2000** [comment]
Was meinst du konkret? Bei allen Subklassen kann man alle Informationen einsehen, man muss einfach vorher den Typ checken

**Comment by sunfl0w** [comment]
ich meine zum Beispiel, dass es eine Methode der Klasse Move gibt, über welche ich die Zielposition des Zuges erfahren kann.

**Comment by Xerus2000** [comment]
SkipMove hat keine Zielposition, daher kann man das leider nicht generell einsehen, sondern eben nur in den Subklassen.

**Comment by Xerus2000** [comment]
Hab in 94f88568 sowas möglich gemacht, falls das ist was du meints?

**Comment by sunfl0w** [comment]
Ja genau. Ist es auch möglich den Typ des bewegten Spielsteins zu erfahren?

**Comment by Xerus2000** [comment]
Dafür musst du schauen ob es SetMove oder DragMove ist und es dann entsprechend auslesen.
