### ISSUE TITLE
TestClient implementieren

### ISSUE THREAD

**Issue by sunfl0w** [CAU-Kiel-Tech-Inf/socha#241]
Beim starten eines Massentests stürzt der Server ab.  Ich habe den Massentest mit zwei Simple-Clients versucht zu starten. Die Meldung dabei besagt, dass der Client, der sich verbunden hat, ein Client für Piranhas ist, der Server aber nur Hive unterstützt.

**Comment by sunfl0w** [comment]
<details>
  <summary>Hier klicken für den output des Servers</summary>
07:52:33,301 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/home/sunfl0w/Desktop/Test/logback.xml]
07:52:33,333 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
07:52:33,333 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
07:52:33,338 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
07:52:33,350 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@387c703b - Will use gz compression
07:52:33,372 |-WARN in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - This appender no longer admits a layout as a sub-component, set an encoder instead.
07:52:33,372 |-WARN in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
07:52:33,372 |-WARN in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
07:52:33,372 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: log/game_server.log
07:52:33,372 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [log/game_server.log]
07:52:33,373 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
07:52:33,373 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
07:52:33,374 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.PatternLayout] for [layout] property
07:52:33,374 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
07:52:33,374 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
07:52:33,374 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
07:52:33,375 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [sc] to INFO
07:52:33,375 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
07:52:33,375 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
07:52:33,375 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
07:52:33,375 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
07:52:33,376 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@224aed64 - Registering current configuration as safe fallback point

07:52:33 INFO  sc.server.Application - Server is starting up...
07:52:33 INFO  sc.server.Configuration - Loading configuration from /home/sunfl0w/Desktop/Test/server.properties
07:52:33 INFO  sc.server.plugins.PluginManager - Loading plugins from: /home/sunfl0w/Desktop/Test/./plugins
07:52:33 INFO  sc.server.plugins.GamePluginInstance - GamePlugin 'Hive' {swc_2020_hive} was loaded.
07:52:33 INFO  sc.server.plugins.PluginManager - Plugin-Cache reloaded. 1 plugins available.
07:52:33 INFO  sc.server.network.NewClientListener - Listening on port 13050 for incoming connections.
07:52:33 INFO  sc.server.network.ClientManager - ClientManager running.
07:52:36 INFO  sc.server.network.NewClientListener - A Client connected...
07:52:36 INFO  sc.server.network.ClientManager - Delegating new client to ClientManager...
07:52:36 INFO  sc.server.network.NewClientListener - Added Client sc.server.network.Client@95efa9d to ReadyQueue.
07:52:36 INFO  sc.server.network.ClientManager - Delegation done.
Security framework of XStream not initialized, XStream is probably vulnerable.
07:52:36 INFO  sc.server.network.Client - Client authenticated as administrator
07:52:36 INFO  sc.server.Lobby - Test mode is set to true
07:52:36 WARN  sc.server.gaming.GameRoomManager - Couldn't find a game of type swc_2019_piranhas
07:52:36 WARN  sc.server.network.Client - An error occured: 
sc.server.plugins.UnknownGameTypeException: Unknown GameType UUID: swc_2019_piranhas (available: swc_2020_hive)
        at sc.server.gaming.GameRoomManager.createGame(GameRoomManager.java:83)
        at sc.server.gaming.GameRoomManager.prepareGame(GameRoomManager.java:192)
        at sc.server.gaming.GameRoomManager.prepareGame(GameRoomManager.java:212)
        at sc.server.Lobby.onRequest(Lobby.kt:77)
        at sc.server.network.Client.notifyOnPacket(Client.java:93)
        at sc.server.network.Client.onObject(Client.java:230)
        at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:114)
        at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:78)
        at java.lang.Thread.run(Thread.java:748)
07:52:36 WARN  sc.server.network.Client - Game closed because of GameLogicException: Unknown GameType UUID: swc_2019_piranhas (available: swc_2020_hive)
07:52:36 INFO  sc.networking.clients.XStreamClient - Client sc.server.network.Client@95efa9d disconnected (Cause: DISCONNECTED)
07:52:36 INFO  sc.networking.clients.XStreamClient - Stopping receiver thread XStreamClient Receive Thread 13 Client
07:52:36 WARN  sc.networking.clients.XStreamClient - Receiver thread is stopping itself
07:52:36 INFO  sc.server.network.ClientManager - Removing client sc.server.network.Client@95efa9d from client manager
07:52:36 INFO  sc.server.Lobby - sc.server.network.Client@95efa9d disconnected.
</details>

**Comment by Xerus2000** [comment]
Massentest? Meinst du den testclient? Der ist noch nicht implementiert.

**Comment by sunfl0w** [comment]
Ja genau den meine ich. Das wird dann wohl der Grund sein.

**Comment by SKoschnicke** [comment]
@Xerus2000 kannst du das machen?

**Comment by Xerus2000** [comment]
theoretisch schon, aber ich bin zurzeit generell zeitlich sehr eingespannt.

**Comment by Xerus2000** [comment]
Sollte wieder laufen, siehe auch https://github.com/CAU-Kiel-Tech-Inf/socha/commit/03cbd09abd9f39769a46889778dedc0228302c7c
