### ISSUE TITLE
Beetle has to move along Swarm

### ISSUE THREAD

**Issue by STAT1C-Sy** [CAU-Kiel-Tech-Inf/socha#242]
![WhatsApp Image 2019-11-01 at 15 36 37](https://user-images.githubusercontent.com/33841685/68032276-a04e1100-fcbd-11e9-8e9a-e31944e15a7e.jpeg)

Beetle (2, 1, -3) wird der Zug nach (3, 0, -3) als valider Move angezeigt, wenn man das ausführt hängt sich das Spiel auf (Man kann zwar Käfer auswählen aber es wird nichts mehr ausgeführt).

Wenn man auf pausieren drückt bekommt man den Spiel vorbei Beetle has to move along swarm error.

**Comment by Agent77326** [comment]
@STAT1C-Sy Kannst du uns hier ein Replay schicken?

**Comment by Xerus2000** [comment]
@Agent77326 das Problem ist klar: Der Move ist nicht erlaubt. Allerdings sollte sich die GUI auch nicht einfach aufhängen wenn ein Fehler auftritt.
