### ISSUE TITLE
Protocol error when sending moves with debug hints

### ISSUE THREAD

**Issue by matthesjh** [CAU-Kiel-Tech-Inf/socha#244]
When a client sends a move that has a debug hint attached, the server terminates the game and responds with the following error message.

```
com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$UnknownFieldException: No such field sc.plugin2020.SetMove.hint
---- Debugging information ----
message             : No such field sc.plugin2020.SetMove.hint
field               : hint
class               : sc.plugin2020.SetMove
required-type       : sc.plugin2020.SetMove
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
line number         : 1
class[1]            : sc.protocol.responses.RoomPacket
required-type[1]    : sc.protocol.responses.RoomPacket
version             : 1.4.11.1
-------------------------------
```

The problem is that the debug hints are removed from the move classes with the first *Hive* release.

**Comment by matthesjh** [comment]
@Xerus2000 Will this be addressed in the near future?

**Comment by Xerus2000** [comment]
The debug hints were never properly implemented if I remember correctly, and afaik they were primarily useful for the multi-Action Moves in Hase & Igel - what would be your use-case here? I am happy to add them back if they make sense.

**Comment by matthesjh** [comment]
They are implemented in the Ruby client too. The debug hints are useful to add some comments to a move, e.g. why the move is selected …

**Comment by Xerus2000** [comment]
Should work now, otherwise write again
