### ISSUE TITLE
GUI akzeptiert ungültige Züge von Käfern.

### ISSUE THREAD

**Issue by sunfl0w** [CAU-Kiel-Tech-Inf/socha#245]
Wie der Titel schon meint, das GUI akzeptiert und führt ungültige Züge von Käfern aus. Mein Client hat einen ungültigen Zug gesendet aufgrund eines Bugs. Er wollte einen Käfer auf ein benachbartes Hindernis ziehen, was ja nicht regelkonform ist. Das GUI hat darauf den Zug akzeptiert und den Zug ausgeführt. Dabei kam es dann zu diesem ironischen Abschnitt im GameState, den ich euch nicht vorenthalten wollte ;) :
 ```
<field x="-3" y="2" z="1" isObstructed="true">
    <piece owner="RED" type="BEETLE" />
</field>
```

Das ist mit dem GUI der Version 20.1.0 passiert. Falls das schon in neueren Versionen behoben wurde, ist dieses Issue natürlich erledigt. Ich update dann mal mein GUI und schaue, ob der Fehler nochmal auftritt.

**Comment by Agent77326** [comment]
Sollte mit https://github.com/CAU-Kiel-Tech-Inf/socha-gui/pull/101 behoben sein, muss nur noch veröffentlicht werden.

**Comment by Xerus2000** [comment]
@sunfl0w das heißt der Zug wurde nicht nur von der GUI akzeptiert, sondern auch vom Server? Dann ist das nämlich noch ein extra-Problem...

**Comment by sunfl0w** [comment]
Ich könnte mich nochmal dransetzen und versuchen es mit den neuesten Versionen zu reproduzieren.

**Comment by Xerus2000** [comment]
das wär super @sunfl0w

**Comment by Xerus2000** [comment]
Hab den Fehler im Server identifiziert, wird in Kürze gefixt.
