### ISSUE TITLE
Manuell gestarteter Client Verbindungsaufbau überprüfen

### ISSUE THREAD

**Issue by Agent77326** [CAU-Kiel-Tech-Inf/socha#247]
![img-2019-09-14-092334](https://media.discordapp.net/attachments/496605132750848004/648155292344909845/image.png?width=502&height=468)

> ###: der antwortet mir dann mit:
> ```
> <protocol>
>   <sc.protocol.responses.CloseConnection/>
> </protocol>
> ```
> ###: laut der dokumenation soll er aber schreiben:
> ```
> <protocol>
>   <joined roomId="871faccb-5190-4e44-82fc-6cdcbb493726" />
> ```

**Comment by Xerus2000** [comment]
Bitte mit mehr Infos neu öffnen wenn das Problem noch besteht. Ich blicke nicht so ganz durch was hier das genaue Problem ist - auf was wird geantwortet? Was wird gesendet? Geht es um den Java Client oder einen eigenen?
