### ISSUE TITLE
Invalid Moves of Spiders are returned by 'getPossibleMoves' 

### ISSUE THREAD

**Issue by Voker13** [CAU-Kiel-Tech-Inf/socha#251]
Invalid moves of spiders are returned by 'getPossibleMoves'.
Those sent moves are correctly marked as wrong by the server.

![SpiderBug](https://user-images.githubusercontent.com/14887314/71987483-90f3c280-322e-11ea-971f-3e831b92356b.png)
I have chosen and send a move from (5, -1, -4) to (5, -2, -3) which is not allowed by the game rules.

[SpiderBug.xml.zip](https://github.com/CAU-Kiel-Tech-Inf/socha/files/4035820/SpiderBug.xml.zip)

**Comment by Voker13** [comment]
Sollte als Bug gekennzeichnet werden.

**Comment by Agent77326** [comment]
@Voker13 danke für dein Feedback, kannst du uns ein Replay geben bei dem dieser Fehler auftritt?
Verstehe ich das richtig, dass der Fehler beim Spielen durch den Client entstanden sind (Soche-Plugin verwendet, nicht von Hand bei der Grafischen Oberfläche?

@Xerus2000 die diff zwischen den beiden ist eigentlich kaum vorhanden, was zumindest die Logikprüfung am Ende betrifft.
[GUI-Implementierung](https://github.com/CAU-Kiel-Tech-Inf/socha-gui/blob/814784f468b5ebce2c3ad1eb6926750380d286d5/src/api/rules/HiveGameRules.ts#L308-L334), [Plugin-Implementierung](https://github.com/CAU-Kiel-Tech-Inf/socha/blob/9c1598a63e391b819fd2b1cf58a5fa6f5f5b5eaa/plugin/src/shared/sc/plugin2020/util/GameRuleLogic.kt#L240-L263)

**Comment by Voker13** [comment]
Der Fehler wird schon im Plugin sein. Da der Zug ja eigl nicht zulässig wäre. Der Server erkennt den falschen Zug ja richtig.
Ich habe btw die selbe Plugin-Implementierung wie oben im link.
Das Replay ist in meiner ersten Nachricht 'gezipt' drin. ;-)

**Comment by Agent77326** [comment]
Hab ich doch glatt das Replay übersehen und 10min lang versucht das zu reproduzieren 😅...

**Comment by Xerus2000** [comment]
@Agent77326 wie ich gesagt habe. Deine Implementation in der GUI lässt ein hin- und zurückgehen im Zug zu, also dass man dasselbe Feld mehrfach betritt. Das wird im Server rausgefiltert mit `filterNot { it in currentPath }`

**Comment by Agent77326** [comment]
Hm... das wird in der GUI aber auch abgefangen durch die Überprüfungen in jedem Schritt, dass keins der Felder eins der vorherigen sein darf:

Mit der Funktion [`this.getNeighbours`](https://github.com/CAU-Kiel-Tech-Inf/socha-gui/blob/814784f468b5ebce2c3ad1eb6926750380d286d5/src/api/rules/HiveGameRules.ts#L15-L17)
Tiefe 1: `this.getNeighbours(board, from)` [...]
Tiefe 2: `this.getNeighbours(board, depth1)` [...] `.filter(e => !e.equal(from)` [...]
Tiefe 3: `this.getNeighbours(board, depth2)` [...] `.filter(e => !e.equal(from) && !e.equal(depth1)` [...]

Tut mir leid ich erkenne da meinen Fehler zumindest nicht, sicher dass es durch die GUI ist? Soweit ich weiß fragt der Client doch den Server und nicht die GUI nach den möglichen Zügen oder?

**Comment by Xerus2000** [comment]
achso, ich habe den Bug falsch verstanden, ich hatte irgendwie gedacht der Move wird in der GUI fälschlicherweise angezeigt. Ich schreibe mal nen Test im Server dazu...

**Comment by Xerus2000** [comment]
@Voker13 hast du auch im client in den libs die neuste version?

**Comment by Xerus2000** [comment]
nevermind, konnte den Bug reproduzieren - das ist seltsam...

**Comment by Xerus2000** [comment]
Ich habe mir ewig über diesen Fehler den Kopf zerbrochen. getPossibleMoves gibt einen Move zurück, bei dem validateMove korrekterweise einen Fehler schmeißt. Allerdings nutzt getPossibleMoves bei der Bestimmung der möglichen Züge selbst bereits validateMove, sodass scheinbar zwei Aufrufe derselben Methode mit den selben Argumenten unterschiedliche Ergebnisse brachten.

Nach etwas Analyse kam ich darauf, dass der Fehler irgendwo im pathfinding der Spinne ist, denn sie überquert dasselbe Feld zweimal, obwohl das die validation nicht zulässt. Im ersten Moment dachte ich, ich hätte damit den Fehler gefunden, aber das erklärte ja noch nicht warum der Move einmal akzeptiert wurde.

Im Debugging sah ich dann, warum ein Feld mehrfach hinzugefügt wurde: Es war verändert - einmal war ne Spinne darauf und einmal nicht. Doch eigentlich sollten doch nur die Koordinaten des Felds verglichen werden, daher sollte das keinen Unterschied machen? Siehe `getAccessibleNeighboursExcept`, speziell `neighbour.coordinates != except`

Doch da kam das nächste Problem ins Spiel: in einer der letzten Änderung hatte ich dafür gesorgt, dass der getter `coordinates` beim Feld das `Field` selbst zurückgibt, statt eines neuen Objekts. Zwar praktisch und schnell, sorgte aber hier in dem speziellen Fall, da überall Fields mitgegeben wurden, dafür, dass die `Field.equals` Methode verwendet wurde, wodurch das Fehlen der Spinne auf dem Feld zu einem neuen möglichen Zug führte.

Bei den Tests dagegen wurde überall nur mit puren `CubeCoordinates` gearbeitet, sodass dort der Fehler nicht auftrat und ein Konflikt entstand.

Es gibt nun 3 Möglichkeiten weiter zu verfahren:

- es so lassen, auf die Gefahr hin, dass solche Probleme erneut auftreten
die Änderung des `coordinates`-getters behebt hier zwar dieses Problem, schließt aber nicht aus, dass in Zukunft wieder scheinbare Coordinates als Fields verglichen werden
- `Field` nicht mehr von CubeCoordinates abstammen lassen, was zwar mühsam wäre aber schon auch irgendwie korrekt - ein Feld *ist* nicht Koordinaten, es *hat* Koordinaten - OOP ist nervig. Eigentlich bräuchte man implizite Konverter für Methodenaufrufe, denn wenn wir das wieder ändern sind auch viele Code-Änderungen fällig...
- Keine eigene `equals`-Method für `Field` definieren - damit würde das System jedes Feld mit gleichen Koordinaten als gleich ansehen, egal was sich darauf befindet. Diese Änderung wäre sehr einfach und dürfte meines Wissens nach auch keine Probleme verursachen.

**Comment by Xerus2000** [comment]
Ist vorerst gefixt - weiteres Verfahren steht noch zur Debatte

**Comment by SKoschnicke** [comment]
Ich bin dafuer, eine eigene `equals` Methode fuer `Field` zu definieren. In der Spiellogik ist es sehr hilfreich, dass Felder gleich sind, wenn deren Koordinaten gleich sind. Man sollte aber zumindest in der Doku auf dieses Verhalten hinweisen.

**Comment by Xerus2000** [comment]
Also willst du, dass wir _keine_ eigene equals-Methode für `Field` definieren, sondern die von `Coordinates` übernommen wird. Dann sind wir uns wohl einig und ich implementiere das so :)

**Comment by SKoschnicke** [comment]
Ja, ich meinte "keine", sorry.

**Comment by maggeno1** [comment]
Die Fehlermeldung taucht bei mir (Version 20.3.0) immer noch auf...

**Comment by Xerus2000** [comment]
Ja, weil die Versionen von server und GUI leider völlig out of sync sind. Wir besprechen das intern nochmal...

**Comment by maggeno1** [comment]
Gibts denn schon einen Anhaltspunkt, wann in etwa mit der Behebung des Fehlers zu rechnen ist? Langsam geht ja die heiße Phase an.

**Comment by SKoschnicke** [comment]
@maggeno1 Im gerade gemachten Release 20.3.2 ist der Bugfix fuer dieses Problem enthalten:
https://github.com/CAU-Kiel-Tech-Inf/socha-gui/releases/tag/20.3.2
https://github.com/CAU-Kiel-Tech-Inf/socha/releases/tag/20.3.2
