### ISSUE TITLE
Evtl. falscher Zug möglich

### ISSUE THREAD

**Issue by 0xhtml** [CAU-Kiel-Tech-Inf/socha#252]
Ich bin mir nicht sicher, ob dieser Zug gültig ist.

Von:
![](https://www.mediafire.com/convkey/63fc/t3i032n68axgai7ag.jpg)

Zu:
![](https://www.mediafire.com/convkey/9a58/8dn3tnrqky4a95jag.jpg)

Damit die Ameise diesen Zug machen  kann, muss sie einmal an der Beere vorbei und ist somit in Mitten des Zuges nicht verbunden, richtig?

**Comment by TiLuHa** [comment]
Ich schätze auch, dass dieser Zug nicht erlaubt sein sollte.

**Comment by Agent77326** [comment]
![PNG-Bild](https://user-images.githubusercontent.com/27964795/72505108-87c2b100-383f-11ea-987c-c31866a4959f.png)
Ist ein korrekter Zug, da zu jedem Zeitpunkt bei einer Bewegung ein Fixpunkt am Schwarm existiert

**Comment by SKoschnicke** [comment]
Siehe auch https://cau-kiel-tech-inf.github.io/socha-enduser-docs/spiele/hive/_z%C3%BCge.html#_voraussetzungen_f%C3%BCr_das_bewegen_eines_spielsteins
