### ISSUE TITLE
Die GUI erlaubt einen ungültigen Zug als Eingabe

### ISSUE THREAD

**Issue by TiLuHa** [CAU-Kiel-Tech-Inf/socha#253]
![image](https://user-images.githubusercontent.com/36930978/72456965-f82cec00-37c5-11ea-8141-de3b27bceb49.png)
![image](https://user-images.githubusercontent.com/36930978/72457007-05e27180-37c6-11ea-90ea-0c427437e8d5.png)
Es ist einem menschlichen Spieler möglich seinen ersten Zug auf eine Beere zu machen. Bei der entsprechenden Abfrage wird dann doch festgestellt, dass das ungültig ist und ROT verliert.

**Comment by Agent77326** [comment]
Es ist eine neue Version als Update bereit, welche diesen Bug behebt
