### ISSUE TITLE
Missmove wurde abgelehnt

### ISSUE THREAD

**Issue by TiLuHa** [CAU-Kiel-Tech-Inf/socha#254]
![image](https://user-images.githubusercontent.com/36930978/72685604-09d70200-3aec-11ea-9d07-f117afa6f865.png)
Übersehe ich da etwas? Mein Client hat einen Missmove gesendet und er wurde allem Anschein nach abgelehnt. Unten Links sieht man, dass ein Missmove gesendet wurde. Das Senden von Zügen funktioniert eigentlich. Man sieht das am vorherigen Zug.

**Comment by Xerus2000** [comment]
es gibt keine missmoves, nur skipmoves. Das wurde anfänglich leider inkonsistent implementiert.
