### ISSUE TITLE
TestGame fails - blocking release

### ISSUE THREAD

**Issue by Agent77326** [CAU-Kiel-Tech-Inf/socha#256]
Due to failing task `:testGame`, release is being blocked:
```
> Task :testGame
Waiting for client 1 to receive game result
task ':testGame' has been running for over 150 seconds - killing server!
> Task :testGame FAILED
Error in task ':testGame' - check the logs in /home/travis/build/CAU-Kiel-Tech-Inf/socha/build/tests
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':testGame'.
> java.lang.Exception: Server terminated unexpectedly!
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings
BUILD FAILED in 4m 51s
35 actionable tasks: 34 executed, 1 up-to-date
```
for full log-access take a look at [travis](https://travis-ci.com/CAU-Kiel-Tech-Inf/socha/builds/145914487).

Testing on local machine with newly fetched repo from master, task `:testGame` seems to time-out as well and remains stuck with no cpu-usage or anything else.

**Comment by Agent77326** [comment]
Can you take a look over it this weekend @Xerus2000?

**Comment by Xerus2000** [comment]
Siehe https://github.com/CAU-Kiel-Tech-Inf/socha/issues/250

**Comment by Xerus2000** [comment]
On my local machine it works without issues, will test with a freshly fetched repo as well...

**Comment by Xerus2000** [comment]
Hm, failed on a second run, weird...

**Comment by xerus2000** [comment]
Fixed by https://github.com/CAU-Kiel-Tech-Inf/socha/commit/d556fa2ef7f4bc7aafe9b3ab45402e0f858a92d2 & 103363226976780ea2aca3c4f1d7f9fdbd2d6d8a
