### ISSUE TITLE
Player deployment fails due to invalid path

### ISSUE THREAD

**Issue by TheNekromate** [CAU-Kiel-Tech-Inf/socha#258]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Alle Rechte vorbehalten.

T:\Workscpace\socha>gradlew.bat check

> Configure project :
Current version: 20.3.2 Game: hive_2020

> Task :player:deploy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':player:deploy'.
> Could not copy file 'T:\Workscpace\socha\player\build\libs\defaultplayer.jar' to 'T:\Workscpace\socha\build\deploy\T:Workscpacesochabuilddeploysimpleclient-hive-20.3.2.jar'.
   > T:\Workscpace\socha\build\deploy\T:Workscpacesochabuilddeploysimpleclient-hive-20.3.2.jar (Die Syntax f³r den Dateinamen, Verzeichnisnamen oder die Datentrõgerbezeichnung ist falsch)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s
19 actionable tasks: 1 executed, 18 up-to-date

T:\Workscpace\socha>gradlew.bat build

> Configure project :
Current version: 20.3.2 Game: hive_2020

> Task :player:deploy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':player:deploy'.
> Could not copy file 'T:\Workscpace\socha\player\build\libs\defaultplayer.jar' to 'T:\Workscpace\socha\build\deploy\T:Workscpacesochabuilddeploysimpleclient-hive-20.3.2.jar'.
   > T:\Workscpace\socha\build\deploy\T:Workscpacesochabuilddeploysimpleclient-hive-20.3.2.jar (Die Syntax f³r den Dateinamen, Verzeichnisnamen oder die Datentrõgerbezeichnung ist falsch)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4s
21 actionable tasks: 1 executed, 20 up-to-date

**Comment by Xerus2000** [comment]
I will look into it. But why are you trying to build the full socha project?
