### ISSUE TITLE
JavaDoc Warnings

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/socha#59]
Beim Bauen mit dem Ant-Script werden viele Warnungen von JavaDoc ausgegeben (`no @return` und sowas). Macht es Sinn, da nachzubessern? Oder wuerde das keinen Mehrwert bringen? Koennte man eventuell auch mittels sowas wie [JAutodoc](http://jautodoc.sourceforge.net/) automatisieren.

**Comment by Xerus2000** [comment]
Das liegt daran, dass teils seltsame JavaDoc vorliegt. Hier nutzt anscheinend jemand einen Generator, der dann teilweise leere Javadoc hinterlässt (z.B ein @return ohne jegliche Beschreibung)
